avalanche:
  image: avaplatform/avalanchego
  container_name: avax
  #command: ["daemon", "--migrate=true", "--enable-pubsub-experiment"]
  command:
    [
      "/avalanchego/build/avalanchego",
      "--db-dir=/data/avax",
#      "--bootstrap-retry-max-attempts=10000",
      "--api-admin-enabled=true",
      "--http-host=0.0.0.0",
      "--bootstrap-retry-enabled",
      "--public-ip=78.46.129.7",
      "--http-allowed-hosts=*"
    ]
  ports:
    - 9650:9650
    - 9651:9651
  volumes:
    - ./avax-data:/data/avax
    - ./staking/staker.key:/root/.avalanchego/staking/staker.key
    - ./staking/staker.crt:/root/.avalanchego/staking/staker.crt
    - ./chain-config.json:/root/.avalanchego/configs/chains/C/config.json
    - ./pruning-data:/root/pruning-data
  restart: unless-stopped
